### ISSUE TITLE
Singer quick tutorial reports class missing: "java.lang.NoClassDefFoundError: com/fasterxml/jackson/annotation/JsonMerge"

### ISSUE THREAD

**Issue by airbots1980** [pinterest/singer#96]
java.lang.NoClassDefFoundError: com/fasterxml/jackson/annotation/JsonMerge
        at com.fasterxml.jackson.databind.introspect.JacksonAnnotationIntrospector.<clinit>(JacksonAnnotationIntrospector.java:50)
        at com.fasterxml.jackson.databind.ObjectMapper.<clinit>(ObjectMapper.java:291)
        at com.twitter.ostrich.admin.CommandHandler.<init>(CommandHandler.scala:83)
        at com.twitter.ostrich.admin.AdminHttpService.<init>(AdminHttpService.scala:470)
        at com.twitter.ostrich.admin.AdminHttpService.<init>(AdminHttpService.scala:453)
        at com.twitter.ostrich.admin.AdminServiceFactory.apply(AdminServiceFactory.scala:64)
        at com.pinterest.singer.metrics.OstrichAdminService.start(OstrichAdminService.java:76)
        at com.pinterest.singer.SingerMain.startOstrichService(SingerMain.java:105)
        at com.pinterest.singer.SingerMain.main(SingerMain.java:166)
Caused by: java.lang.ClassNotFoundException: com.fasterxml.jackson.annotation.JsonMerge
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        ... 9 more
2020-09-28 06:42:15,074 [SingerHeartbeat] (com.pinterest.singer.heartbeat.HeartbeatGenerator:46) ERROR Caught exception while sending heartbeat message
org.apache.kafka.common.KafkaException: Producer closed while send in progress
        at org.apache.kafka.clients.producer.KafkaProducer.doSend(KafkaProducer.java:864)
        at org.apache.kafka.clients.producer.KafkaProducer.send(KafkaProducer.java:841)
        at org.apache.kafka.clients.producer.KafkaProducer.send(KafkaProducer.java:728)
        at com.pinterest.singer.heartbeat.HeartbeatKafkaWriter.write(HeartbeatKafkaWriter.java:44)
        at com.pinterest.singer.heartbeat.HeartbeatGenerator.run(HeartbeatGenerator.java:43)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.kafka.common.KafkaException: Requested metadata update after close
        at org.apache.kafka.clients.Metadata.awaitUpdate(Metadata.java:200)
        at org.apache.kafka.clients.producer.KafkaProducer.waitOnMetadata(KafkaProducer.java:981)
        at org.apache.kafka.clients.producer.KafkaProducer.doSend(KafkaProducer.java:861)
        ... 11 more
2020-09-28 06:42:15,078 [Thread-3] (com.pinterest.singer.writer.KafkaProducerMetricsMonitor:58) WARN  KafkaProducerMetricsMonitor thread interrupted, exiting
2020-09-28 06:42:15,083 [LogWriter:-tmp-singer_tutorial-kafka_server.txt: 1] (com.pinterest.singer.writer.KafkaWritingTask:127) ERROR Failed to write 5 messages to kafka
java.lang.IllegalStateException: Cannot perform operation after producer has been closed
        at org.apache.kafka.clients.producer.KafkaProducer.throwIfProducerClosed(KafkaProducer.java:848)
        at org.apache.kafka.clients.producer.KafkaProducer.doSend(KafkaProducer.java:857)
        at org.apache.kafka.clients.producer.KafkaProducer.send(KafkaProducer.java:841)
        at org.apache.kafka.clients.producer.KafkaProducer.send(KafkaProducer.java:728)
        at com.pinterest.singer.writer.KafkaWritingTask.call(KafkaWritingTask.java:84)
        at com.pinterest.singer.writer.KafkaWritingTask.call(KafkaWritingTask.java:35)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
2020-09-28 06:42:15,084 [Thread-0] (com.pinterest.singer.SingerMain$SingerCleanupThread:93) ERROR metricsPusher was not initialized properly.

**Comment by ambud** [comment]
Please try the latest version, there shouldn't be a dependency issue.
